# Generated by Django 4.0.6 on 2022-07-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cat_type',
            field=models.IntegerField(choices=[(1, 'Седан'), (2, 'Хэтбек'), (3, 'Универсал'), (4, 'Купе')], verbose_name='Car_Type'),
        ),
    ]
