# Generated by Django 4.0.6 on 2022-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_cat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(db_index=True, max_length=65, unique=True, verbose_name='Vin'),
        ),
    ]
